Enable adress translator
composable-systems/dropwizard-cassandra pull request #26
Opened 2017-04-03 14:21 UTC by MALPI

I added a factory to enable configuration of [AddressTranslators](https://docs.datastax.com/en/drivers/java/2.0/com/datastax/driver/core/policies/EC2MultiRegionAddressTranslater.html).

I therefore created a new `connect` package since it didn't seem to fit anywhere else.

See Issue #25

2017-04-03 15:03 UTC, stuartgunter requested changes
Thanks for the PR - it's a great help!

I've added some comments - primarily to keep the coding style consistent. Please could you take a look and either fix / add your own comments?

Much appreciated.

2017-04-03 15:03 UTC, stuartgunter commented on src/main/java/systems/composable/dropwizard/cassandra/CassandraFactory.java
> +    private Optional<AddressTranslatorFactory> translatorOptions = Optional.empty();
Please can we call this `addressTranslator` instead.

2017-04-03 15:03 UTC, stuartgunter commented on src/main/java/systems/composable/dropwizard/cassandra/CassandraFactory.java
> +
Please don't add extra whitespace. The PR should conform to the existing code styles used.

2017-04-03 15:03 UTC, stuartgunter commented on src/main/java/systems/composable/dropwizard/cassandra/CassandraFactory.java
> +
Please don't add extra whitespace. The PR should conform to the existing code styles used.

2017-04-03 15:03 UTC, stuartgunter commented on src/main/java/systems/composable/dropwizard/cassandra/connect/AddressTranslatorFactory.java
> +  AddressTranslator build();
Please use the same indentation (4 spaces, not 2) as existing code to maintain uniformity. The same applies to other code in this PR.

2017-04-03 15:03 UTC, stuartgunter commented on src/main/java/systems/composable/dropwizard/cassandra/connect/EC2MultiRegionAddressTranslatorFactory.java
> +@JsonTypeName("ec2MultiRegionAddressTranslator")
Please rename to `ec2MultiRegion` (to match naming formats in use for other factories)... the `AddressTranslator` part is redundant.

2017-04-03 15:03 UTC, stuartgunter commented on src/main/java/systems/composable/dropwizard/cassandra/connect/IdentityTranslatorFactory.java
> +@JsonTypeName("identityTranslator")
What do we gain by defining this type? It looks like its equivalent to not specifying an `addressTranslator`.

2017-04-03 15:03 UTC, stuartgunter commented on src/test/java/systems/composable/dropwizard/cassandra/connect/Ec2MultiRegionAddressTranslatorFactoryTest.java
> +public class Ec2MultiRegionAddressTranslatorFactoryTest {
Please capitalise `EC2` (i.e. no lowercase `c`) to conform to existing naming conventions.

2017-04-03 15:03 UTC, stuartgunter commented on src/test/java/systems/composable/dropwizard/cassandra/connect/IdentityTranslatorFactoryTest.java
> +  public void buildsPolicyWithChildPolicy() throws Exception {
Please define a more suitable name for this test.

2017-04-03 15:03 UTC, stuartgunter commented on src/test/java/systems/composable/dropwizard/cassandra/connect/Ec2MultiRegionAddressTranslatorFactoryTest.java
> +  public void buildsPolicyWithChildPolicy() throws Exception {
Please define a more suitable name for this test.

2017-04-03 15:03 UTC, stuartgunter commented on src/main/java/systems/composable/dropwizard/cassandra/connect/AddressTranslatorFactory.java
> +package systems.composable.dropwizard.cassandra.connect;
Please could you rename this package... `connect` is a verb, which doesn't fit nicely with package names. Perhaps something like `connection` or `network`?

2017-04-03 18:32 UTC, MALPI commented
@stuartgunter I applied all changes you mentioned. Thanks for your quick response.

I am really happy contribute!

2017-04-04 13:41 UTC, stuartgunter approved these changes

2017-04-04 13:43 UTC, merged

2017-04-04 14:13 UTC, MALPI commented
@stuartgunter when will a new release be triggered?

2017-04-04 14:48 UTC, stuartgunter commented
@MALPI I have one other PR that I'd like to merge before doing the next release, but it should go out in the next few days.

2017-04-07 08:46 UTC, MALPI commented
@stuartgunter any update?

2017-04-13 06:08 UTC, stuartgunter commented
I released a new version yesterday, so you should see it in Maven Central now. Please let me know if you have any problems with the latest version.